version: '3.0'
networks:
  compose_networks:
    driver: "bridge"
services:
  web:
    build: ./backend
    ports:
     - "3000:3000"
    links:
      - redis
    networks:
      - compose_networks

  redis:
   image: redis
   command: redis-server --port 6379
   container_name: redis
   labels:
    - "name=redis"
    - "mode = standalone"
   ports:
    - "6379:6379" 
   networks:
    - compose_networks