version: '3.0'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    networks:
      - compose-networks

  redis:
   image: redis
   command: redis-server --port 6379
   container_name: redis
   labels:
    - "name=redis"
    - "mode = standalone"
   ports:
    - "6379:6379"

networks:
  compose-networks: